# Generated by Django 5.2.9 on 2025-12-07 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAccident', models.DateField(default='1970-01-01')),
                ('Commentaire', models.CharField(default='Undefined', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomAnimal', models.CharField(max_length=200)),
                ('Espece', models.CharField(default='Undefined', max_length=200)),
                ('DateNaissance', models.DateField(default='1970-01-01')),
                ('DateArriveeZoo', models.DateField(default='1970-01-01')),
                ('DateDepartZoo', models.DateField(default='1970-01-01')),
                ('Age', models.IntegerField()),
                ('RegimeAlimentaire', models.CharField(default='Undefined', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Soigneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(default='tartempion', max_length=200)),
                ('Prenom', models.CharField(default='tartempion', max_length=200)),
                ('Role', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdVaccin', models.BigIntegerField(default='0000')),
                ('NomVaccin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('IdVisite', models.AutoField(primary_key=True, serialize=False)),
                ('DateDerniereVisite', models.DateField(blank=True, null=True)),
                ('DateDernierVaccin', models.DateField(blank=True, null=True)),
                ('Pathologie', models.CharField(blank=True, max_length=32, null=True)),
                ('DescriptionVisite', models.CharField(blank=True, max_length=255, null=True)),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.animal')),
                ('IdVaccin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.vaccin')),
            ],
        ),
    ]
