# Generated by Django 5.2.9 on 2025-12-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdAnimal', models.CharField(max_length=200)),
                ('NomAnimal', models.CharField(max_length=200)),
                ('Espece', models.CharField(default='Undefined', max_length=200)),
                ('DateNaissance', models.DateField(default=1968)),
                ('DateArriveeZoo', models.DateField(default=1968)),
                ('DateDepartZoo', models.DateField(default=1968)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
