# Generated by Django 5.2.9 on 2025-12-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='IdAnimal',
        ),
    ]
