# Generated by Django 5.2.9 on 2025-12-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animal',
            table='zoo_animal',
        ),
    ]
