# Generated by Django 5.2.9 on 2025-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_remove_animal_idanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='RegimeAlimentaire',
            field=models.CharField(default='Undefined', max_length=200),
        ),
    ]
