# Generated by Django 5.2.9 on 2025-12-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_alter_animal_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visite',
            old_name='IdVaccin',
            new_name='Vaccin',
        ),
        migrations.RemoveField(
            model_name='vaccin',
            name='IdVaccin',
        ),
    ]
