# Generated by Django 5.2.9 on 2025-12-07 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_animal_regimealimentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soigneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(default='tartempion', max_length=200)),
                ('Prenom', models.CharField(default='tartempion', max_length=200)),
                ('Role', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdVaccin', models.BigIntegerField(default='0000')),
                ('NomVaccin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('IdVisite', models.AutoField(primary_key=True, serialize=False)),
                ('DateDerniereVisite', models.DateField(blank=True, null=True)),
                ('DateDernierVaccin', models.DateField(blank=True, null=True)),
                ('DateDerniereEchographie', models.DateField(blank=True, null=True)),
                ('Pathologie', models.CharField(blank=True, max_length=32, null=True)),
                ('DescriptionVisite', models.CharField(blank=True, max_length=255, null=True)),
                ('IdVaccin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.vaccin')),
                ('Prenom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.soigneur')),
            ],
        ),
    ]
