# Generated by Django 5.2.9 on 2025-12-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_rename_idvaccin_visite_vaccin_remove_vaccin_idvaccin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soigneur',
            name='Role',
        ),
        migrations.AddField(
            model_name='soigneur',
            name='Age',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='soigneur',
            name='Specialisation',
            field=models.CharField(default='tartempion', max_length=200),
        ),
    ]
