# Generated by Django 5.2.9 on 2025-12-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_soigneur_vaccin_visite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAccident', models.DateField(default=1968)),
                ('Commentaire', models.CharField(default='Undefined', max_length=200)),
            ],
        ),
    ]
