# Generated by Django 5.2.9 on 2025-12-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_remove_soigneur_role_soigneur_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visite',
            name='Vaccin',
        ),
        migrations.DeleteModel(
            name='Vaccin',
        ),
    ]
