# Generated by Django 5.2.9 on 2025-12-08 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_remove_visite_vaccin_delete_vaccin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visite',
            name='IdVisite',
        ),
        migrations.AddField(
            model_name='visite',
            name='Soigneur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoo.soigneur'),
        ),
        migrations.AddField(
            model_name='visite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
