# Generated by Django 5.2.9 on 2025-12-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_remove_visite_idvisite_visite_soigneur_visite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='Soigneur',
            field=models.CharField(default='Soigneur', max_length=32),
        ),
    ]
